Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow ssh to client host
        VpcId: !ImportValue VpcId
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  Instance:      
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-0747bdcabd34c712a
      InstanceType: t2.micro
      KeyName: kp-victor
      SecurityGroupIds: 
        - !Ref InstanceSecurityGroup
      SubnetId: !ImportValue PublicSubnetId
      Tags: 
        - Key: Name
          Value: instancia-victor
